The How it works and PainPoints sections were made
Hyper-Island-Collaborate-Session/grey-matter-project pull request #13
Opened 2024-04-22 11:02 UTC by setayeshnri

The How it works and PainPoints sections were made according to last weeks design. in order to make these some logo's were added to assets and also some custom values to talwind config.

2024-04-22 11:33 UTC, elen-oz requested changes
I leave some comments, can you check it?

2024-04-22 11:33 UTC, elen-oz commented on tailwind.config.js
> +        secondaryDark: '#364208',
but we don't have secondary dark color in figma design, and there is no #364208 color - check it this may have been changed. 
all colors are already here, so use existing ones

2024-04-22 11:33 UTC, elen-oz commented on tailwind.config.js
> +        secondaryDark: '#364208',
the link with colors: https://www.figma.com/file/Uy6C8HndszucAmAWO8XXhM/Team-10---Sketches?type=design&node-id=364-30&mode=design&t=vs9bmkkckJEmsvxL-0

2024-04-22 11:33 UTC, elen-oz commented on src/sections/PainPoints.jsx
> +    <>
this is a great place for a semantic tag `<section>`, no need to use react-fragment

2024-04-22 11:33 UTC, elen-oz commented on src/sections/HowItWorks.jsx
> +import fingerprint from '../assets/Fingerprint.png';
we can also download from figma SVG format - to would be nicer for performance then PNG

2024-04-22 11:33 UTC, elen-oz commented on src/sections/HowItWorks.jsx
> +    <>
(2) this is a great place for a semantic tag` <section>`, no need to use `react-fragment` (`<></>`)

2024-04-22 11:33 UTC, elen-oz commented on src/App.jsx
> +      <PainPoints/>
it looks like you deleted previous tags `Content` and `Footer`, why?

2024-04-22 11:33 UTC, elen-oz commented on package.json
> +    "build": "^0.1.4",
do we need new dependency?

2024-04-22 11:33 UTC, elen-oz commented on tailwind.config.js
> +      },
when you are adding **numbers as variables**, _you are rewriting existing ones_ - in could lead to **unexpected behavior elsewhere** in the code. So try to avoid that and please use a custom` [NNpx]` - if you need it direct in `className`

2024-04-22 11:59 UTC, osmankelifa approved these changes

2024-04-22 12:16 UTC, setayeshnri commented on tailwind.config.js
> +      },
I checked before naming them there are no margins under those names.
should i still change them?

2024-04-22 12:30 UTC, elen-oz commented on tailwind.config.js
> +      },
It doesn’t matter if we already have puddings or margins. This is bad practice in general. 
In Tailwindcss they have certain measurements (0.25rem). If you change it, unexpected behaviour will be later.

2024-04-22 12:36 UTC, elen-oz commented on tailwind.config.js
> +        secondaryDark: '#364208',
All the colors that we have in this file are presented in the design. There cannot be any extra colors or missing colors here.
Use existing `primaryDark` - when designers change it in Figma, we change exactly primaryDark in the code and your code will not have be rewritten.

2024-04-22 13:28 UTC, elen-oz commented on src/App.jsx
> +      <PainPoints/>
`<HowItWorks/>` and `<PainPoints/>` should be inside `Content`

2024-04-22 16:54 UTC, elen-oz requested changes

2024-04-22 16:54 UTC, elen-oz commented on src/sections/HowItWorks.jsx
> +    <div className="font-main">
in prev review my point was in replacing `<>` by `<section>`; the thing is that `fragment <>` and `<div>` - are almost the same. 
So, let's replace the current external `<div className="font-main">` with `<section className="font-main">`. Tag `<section>` is also a block element as `<div>`, but the difference is in semantic meaning.

2024-04-22 16:54 UTC, elen-oz commented on src/sections/PainPoints.jsx
> +    <div className="bg-primaryDark font-main pt-0.5 pb-3 mb-64 h-painpoints">
here is the same comment as in HowItWorks.jsx component:
let's replace `<div className="bg-primaryDark font-main pt-0.5 pb-3 mb-64 h-painpoints">` with `<section className="bg-primaryDark font-main pt-0.5 pb-3 mb-64 h-painpoints">`

2024-04-22 16:54 UTC, elen-oz commented on tailwind.config.js
> +        primaryDark: '#364208',
here I told to use the existing color, not change it. Let's return color as it displayed in designers pallet `#5F750B`

2024-04-22 16:54 UTC, elen-oz commented on tailwind.config.js
> +        pondeo: '30px',
I see that you tried to avoid repetitives in the code and you separate it here. But to create new variable _for each_ element not very good solution. It will be better _to split the code on different elements_ with we can use several times, like in your code: create a new component Card -- but it will be later not now.

Now, let's **use all this measurements in the code directly**, 
so delete these vars and in className replace all these variables with these values.

like: margin-[30px], lineHeight-[30px].... and so on

2024-04-23 08:09 UTC, elen-oz approved these changes
💖

2024-04-23 08:14 UTC, Sheriff702 approved these changes

2024-04-23 08:15 UTC, Sheriff702 commented
Looks good to me ☺️

2024-04-23 08:18 UTC, merged