Refactor Navbar and Hero components Then make them responsive
Hyper-Island-Collaborate-Session/grey-matter-project pull request #16
Opened 2024-04-22 23:02 UTC by Sheriff702

Refactor Navbar and Hero components Then make them responsive. i did work some on each components that i've done. i should do them seperetly on new branch but i was to lazy :P

2024-04-23 08:30 UTC, elen-oz approved these changes

2024-04-23 08:49 UTC, elen-oz requested changes

2024-04-23 08:49 UTC, elen-oz commented on src/components/Navbar.jsx
> +    <div className="flex justify-between items-center py-2 px-4 bg-neutral-900 shadow-md border-b border-gray-600">
we need to use DS colors, not tailwind - they are different
and why did you put here gray border-bottom?

2024-04-23 08:59 UTC, elen-oz commented on src/sections/Hero.jsx
>          {styles.map((s, i) => (
47 line - bg-lime-600 = #65A30D
but we are using now primaryDark: '#5F750B'
use our DS colors, not tailwind

2024-04-23 08:59 UTC, elen-oz commented on src/sections/Hero.jsx
> +        <div className="bg-neutral-900 text-white h-screen flex flex-col items-center justify-evenly">
same here: we use black: black: '#131313'
not bg-neutral-900 - which is #171717

2024-04-23 09:02 UTC, setayeshnri commented on tailwind.config.js
It's better to add custom values in classNames instead of adding the in config and it is bad practice to name the values numbers.

2024-04-23 09:17 UTC, elen-oz commented on src/components/Navbar.jsx
> +    <div className="flex justify-between items-center py-2 px-4 bg-neutral-900 shadow-md border-b border-gray-600">
I used for `<body>` bg our black color, so there is no need to specify it everywhere where it suppose to be `#131313`. If we delete it it will work.

`flex justify-between items-center py-2 px-4 shadow-lg shadow-[#000]`

2024-04-23 09:18 UTC, elen-oz commented on src/sections/Hero.jsx
> +        <div className="bg-neutral-900 text-white h-screen flex flex-col items-center justify-evenly">
also no need to specify bg color here, we can just remove it

2024-04-23 18:53 UTC, Sheriff702 commented on src/sections/Hero.jsx
>          {styles.map((s, i) => (
this is for the small balls so this is something else.

2024-04-23 18:59 UTC, Sheriff702 commented on tailwind.config.js
Some values you need to add them to config since it is not within tailwind default so you need to extend. like the spacing i put in.

2024-04-23 19:21 UTC, Sheriff702 reviewed
Changed some stuff

2024-04-23 19:52 UTC, osmankelifa approved these changes

2024-04-24 06:51 UTC, elen-oz requested changes

2024-04-24 06:51 UTC, elen-oz commented on src/components/StatsSquare.jsx
> +  <div className="w-44 h-28 p-2 bg-neutral-900 rounded-2xl border-2 border-slate-50 flex flex-col items-center justify-around">
you missed bg here 🍫

2024-04-24 08:05 UTC, elen-oz approved these changes

2024-04-24 08:05 UTC, merged