Prospects fixed
Hyper-Island-Collaborate-Session/grey-matter-project pull request #32
Opened 2024-04-26 23:19 UTC by setayeshnri

fixed the responsiveness of Prospects and added the gradient bg to how it works.

2024-04-27 07:54 UTC, elen-oz requested changes

2024-04-27 07:54 UTC, elen-oz commented on src/sections/HowItWorks/index.jsx
> +      <div className="w-full flex justify-center bg-gradient-to-b p-4 from-transparent via-[#5F750B] to-transparent">
#5F750B - new color? we have all colours on tailwind.config file, let's use one of those

2024-04-27 07:54 UTC, elen-oz commented on src/sections/HowItWorks/index.jsx
> +        <div className="w-full h-full  md:w-[700px] lg:w-[860px] xl:w-[1200px]  shadow-[0px_0px_0px_1px_#00000033,0px_2px_0px_0px_#00000014,0px_2px_6px_0px_#0000001a]">
new shadow for the video -  do we need it?

2024-04-27 08:20 UTC, setayeshnri commented on src/sections/HowItWorks/index.jsx
> +        <div className="w-full h-full  md:w-[700px] lg:w-[860px] xl:w-[1200px]  shadow-[0px_0px_0px_1px_#00000033,0px_2px_0px_0px_#00000014,0px_2px_6px_0px_#0000001a]">
it's in the design, we need it.

2024-04-27 10:53 UTC, elen-oz commented on src/sections/HowItWorks/index.jsx
> +        <div className="w-full h-full  md:w-[700px] lg:w-[860px] xl:w-[1200px]  shadow-[0px_0px_0px_1px_#00000033,0px_2px_0px_0px_#00000014,0px_2px_6px_0px_#0000001a]">
I don't see any shadow around video on design and I dont see any difference with and without that shadow on the website

2024-04-27 11:01 UTC, setayeshnri commented on src/sections/HowItWorks/index.jsx
> +        <div className="w-full h-full  md:w-[700px] lg:w-[860px] xl:w-[1200px]  shadow-[0px_0px_0px_1px_#00000033,0px_2px_0px_0px_#00000014,0px_2px_6px_0px_#0000001a]">
If you click on the video there are 3 drop shadows on it! they're subtle but they help with making the video pop out more.

2024-04-28 10:24 UTC, elen-oz approved these changes

2024-04-28 15:38 UTC, Sheriff702 approved these changes

2024-04-28 15:38 UTC, merged